spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    username: sa
    url: jdbc:h2:mem:asm-rdb
    driver-class-name: org.h2.Driver

---
spring:
  profiles: prod
  datasource:
    username: sa
    url: jdbc:h2:mem:asm-rdb-prod
    driver-class-name: org.h2.Driver
